CREATE TABLE `foster_applications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50),
	`address` text,
	`city` varchar(100),
	`zip` varchar(20),
	`animalPreference` varchar(100),
	`fosterType` varchar(255),
	`homeType` varchar(100),
	`hasChildren` boolean DEFAULT false,
	`hasOtherPets` boolean DEFAULT false,
	`otherPetsDescription` text,
	`experience` text,
	`availability` varchar(255),
	`additionalInfo` text,
	`status` enum('new','contacted','approved','active','inactive') NOT NULL DEFAULT 'new',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `foster_applications_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `volunteer_submissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`firstName` varchar(100) NOT NULL,
	`lastName` varchar(100) NOT NULL,
	`email` varchar(320) NOT NULL,
	`phone` varchar(50),
	`address` text,
	`city` varchar(100),
	`zip` varchar(20),
	`availability` varchar(255),
	`interests` text,
	`experience` text,
	`howHeard` varchar(255),
	`status` enum('new','contacted','active','inactive') NOT NULL DEFAULT 'new',
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `volunteer_submissions_id` PRIMARY KEY(`id`)
);
